# Generated by Django 3.2.7 on 2022-03-27 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_Rating', models.AutoField(primary_key=True, serialize=False, verbose_name='id_Rating')),
                ('qualification', models.PositiveIntegerField(default=1, verbose_name='Calificación')),
                ('review', models.TextField(max_length=200, verbose_name='Reseña')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'Rating',
                'ordering': ['id_Rating'],
            },
        ),
    ]
