# Generated by Django 3.2.7 on 2021-12-14 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('id_doc', models.IntegerField(verbose_name='Identificación')),
                ('phone_number', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('names', models.CharField(max_length=60, verbose_name='Nombres')),
            ],
            options={
                'verbose_name': 'Mensajero',
                'verbose_name_plural': 'Mensajeros',
                'db_table': 'Mensajero',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'db_table': 'Tipo_de_documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('products', models.CharField(max_length=80, verbose_name='productos')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'db_table': 'Metodos_de_pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(verbose_name='Cliente')),
                ('product', models.CharField(max_length=60, verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trademarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuario',
                'db_table': 'Tipos_de_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField(verbose_name='Identificación')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('documentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.documenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usertype')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commentary', models.TextField(verbose_name='comentario')),
                ('Payment_Methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.paymentmethods')),
            ],
            options={
                'verbose_name': 'Carrito de compra',
                'verbose_name_plural': 'Carrito de compras',
                'db_table': 'Carrito_de_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.category')),
                ('documentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.documenttype')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.inventory')),
                ('paymentmethods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.paymentmethods')),
                ('shopingcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.shopingcart')),
                ('trademarks', models.ManyToManyField(to='modelos.Trademarks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usertype')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('product', models.CharField(max_length=60, verbose_name='Producto')),
                ('deliverycourier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.deliverycourier')),
            ],
            options={
                'verbose_name': 'Orden de pago',
                'verbose_name_plural': 'Órdenes de pago',
                'db_table': 'Orden_de_pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalValue', models.IntegerField(verbose_name='Valor total')),
                ('orderDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de pedido')),
                ('deliveryDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de entrega')),
                ('invoiceCode', models.CharField(max_length=40, verbose_name='Código de factura')),
                ('productQuantity', models.PositiveIntegerField(verbose_name='Cantidad del producto')),
                ('product', models.CharField(max_length=60, verbose_name='Producto')),
                ('paymentmethods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.paymentmethods')),
                ('payorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.payorder')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='deliverycourier',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.sale'),
        ),
    ]
