# Generated by Django 3.2.7 on 2022-03-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
        ('user', '0003_alter_user_web_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_web',
            name='documentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.documenttype'),
        ),
    ]
