# Generated by Django 3.2.7 on 2022-03-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_web_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_web',
            name='address',
        ),
    ]
