# Generated by Django 3.2.7 on 2021-09-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': ' Usuarios',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
    ]
