# Generated by Django 3.2.7 on 2022-03-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('descrip', models.TextField(max_length=500, verbose_name='Descripción')),
                ('weight', models.CharField(max_length=50, verbose_name='Peso')),
                ('dimensions', models.CharField(max_length=100, verbose_name='Dimensiones')),
                ('size', models.CharField(max_length=100, verbose_name='Tamaño')),
                ('flavor', models.CharField(max_length=100, verbose_name='Sabor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='Veterianimal/static/imagenes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.category')),
                ('trademarks', models.ManyToManyField(to='modelos.Trademarks')),
            ],
        ),
    ]
