# Generated by Django 3.2.7 on 2022-03-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
        ('categories', '0002_remove_category_products'),
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='Producto',
        ),
        migrations.CreateModel(
            name='Servicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='Veterianimal/static/imagenes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('trademarks', models.ManyToManyField(to='modelos.Trademarks')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
                'ordering': ['id'],
            },
        ),
    ]
