# Generated by Django 3.2.7 on 2022-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.CharField(max_length=50, verbose_name='Sabor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=20, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=10, verbose_name='Peso'),
        ),
    ]
