# Generated by Django 3.2.7 on 2022-03-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220327_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicies',
            name='descrip',
            field=models.TextField(default='', max_length=500, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
