# Generated by Django 3.2.7 on 2022-03-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_servicies_descrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicies',
            options={},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicies',
            table=None,
        ),
    ]
