# Generated by Django 3.2.7 on 2022-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
        ('products', '0005_auto_20220327_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sabor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trademarks',
            field=models.ManyToManyField(blank=True, to='modelos.Trademarks'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Peso'),
        ),
        migrations.DeleteModel(
            name='Servicies',
        ),
    ]
